# Generated by Django 6.0.1 on 2026-02-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='otp',
        ),
    ]
