# Generated by Django 6.0.1 on 2026-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_opdday_confirmation_prompt_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='two_ahead_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opdday',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opdday',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opdday',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
