# Generated by Django 6.0.1 on 2026-02-12 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='booking.district')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='booking.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('MORNING', 'Morning (10AM - 12PM)'), ('EVENING', 'Evening (2PM - 5PM)')], max_length=10)),
                ('token_number', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.patient')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.department')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'booking_date'), name='one_token_per_patient_per_day'), models.UniqueConstraint(fields=('department', 'session', 'booking_date', 'token_number'), name='unique_token_per_session_per_day')],
            },
        ),
    ]
