# Generated by Django 6.0.1 on 2026-02-13 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='one_token_per_patient_per_day',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_token_per_session_per_day',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning (10AM - 12PM)'), ('evening', 'Evening (2PM - 5PM)')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('department', 'session', 'booking_date', 'token_number')},
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('patient', 'booking_date'), name='unique_patient_per_day'),
        ),
    ]
