# Generated by Django 6.0.1 on 2026-03-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_confirmation_time_booking_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('consulting', 'Consulting'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
