# Generated by Django 5.1.5 on 2026-04-23 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('booking', '0007_booking_two_ahead_notified_opdday_is_paused_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('morning', 'Morning only'), ('evening', 'Evening only'), ('all', 'Full Day')], default='all', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.doctor')),
            ],
            options={
                'ordering': ['-date', 'session'],
                'unique_together': {('doctor', 'date', 'session')},
            },
        ),
    ]
